outfit_project/outfit_project/Models/supplier.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outfit_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier()
        {
            this.product = new HashSet<product>();
        }
    
        public long id_supplier { get; set; }
        public string name { get; set; }
        public string phone_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product { get; set; }
    }
}

outfit_project/outfit_project/Controllers/suppliersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using outfit_project.Models;

namespace outfit_project.Controllers
{
    public class suppliersController : Controller
    {
        private outfitEntities1 db = new outfitEntities1();

        // GET: suppliers
        public ActionResult Index()
        {
            return View(db.supplier.ToList());
        }

        // GET: suppliers/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            supplier supplier = db.supplier.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // GET: suppliers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: suppliers/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_supplier,name,phone_number")] supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.supplier.Add(supplier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(supplier);
        }

        // GET: suppliers/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            supplier supplier = db.supplier.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: suppliers/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_supplier,name,phone_number")] supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supplier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        // GET: suppliers/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            supplier supplier = db.supplier.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            supplier supplier = db.supplier.Find(id);
            db.supplier.Remove(supplier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

outfit_project/outfit_project/Views/suppliers/Create.cshtml
@model outfit_project.Models.supplier

@{
    ViewBag.Title = "Create";
}

<h2>Crear Proveedor</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">assignment_ind</i>
                @Html.LabelFor(model => model.name, "Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">call</i>
                @Html.LabelFor(model => model.phone_number, "Teléfono", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row center">
            <div class="col s6 m6 l6">
                <button class="btn waves-effect waves-light" type="submit" name="action">Crear<i class="material-icons right">save</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>

    </div>
}

outfit_project/outfit_project/Views/suppliers/Delete.cshtml
@model outfit_project.Models.supplier

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Seguro que desea eliminar este proveedor?</h3>
<div>
    <table class="striped">

        <thead>
            <tr>
                <th>Nombre</th>
                <th>Telefono</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th>@Html.DisplayFor(model => model.name)</th>
                <th>@Html.DisplayFor(model => model.phone_number)</th>
            </tr>
        </tbody>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="row center">
            <div class="col s12 m12 l12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Eliminar<i class="material-icons right">delete_forever</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>
    }
</div>

outfit_project/outfit_project/Views/suppliers/Details.cshtml
@model outfit_project.Models.supplier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>supplier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_supplier }) |
    @Html.ActionLink("Back to List", "Index")
</p>

outfit_project/outfit_project/Views/suppliers/Edit.cshtml
@model outfit_project.Models.supplier

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Proveedor</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_supplier)

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">assignment_ind</i>
                @Html.LabelFor(model => model.name, "Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">call</i>
                @Html.LabelFor(model => model.phone_number, "Teléfono", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row center">
            <div class="col s6 m6 l6">
                <button class="btn waves-effect waves-light" type="submit" name="action">Guardar Cambios<i class="material-icons right">save</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>

    </div>
}

outfit_project/outfit_project/Views/suppliers/Index.cshtml
@model IEnumerable<outfit_project.Models.supplier>

@{
    ViewBag.Title = "Index";
}

<h2>Proveedores</h2>

<form class="col s6">
    <div class="row">
        <div class="input-field col s3">
            <input placeholder="Buscar proveedor" id="SearchSupplier" name="SearchSupplier" type="text" class="validate">
        </div>
    </div>
</form>

<div class="row">
    <div class="col s1 m1 l1 center-align">
        <a class="black-text" href='@Url.Action("Create", "suppliers")'><i class="material-icons icon medium">add_circle</i></a>
    </div>
</div>

<table class="striped" id="supplierList">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Telefono</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.name)</td>
                <td>@Html.DisplayFor(modelItem => item.phone_number)</td>
                <td>
                    <a class="black-text" href='@Url.Action("Edit", "suppliers", new { id = item.id_supplier })'><i class="material-icons">edit</i></a>
                </td>
                <td>|</td>
                <td>
                    <a class="black-text" href='@Url.Action("Delete", "suppliers", new { id = item.id_supplier})'><i class="material-icons">delete</i></a>
                </td>
            </tr>
        }
    </tbody>

</table>