outfit_project/outfit_project/Models/reservation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outfit_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservation()
        {
            this.appointment = new HashSet<appointment>();
            this.sale = new HashSet<sale>();
        }
    
        public long id_reservation { get; set; }
        public long id_customer { get; set; }
        public long id_product { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointment { get; set; }
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale> sale { get; set; }
    }
}

outfit_project/outfit_project/Controllers/reservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using outfit_project.Models;

namespace outfit_project.Controllers
{
    public class reservationsController : Controller
    {
        private outfitEntities1 db = new outfitEntities1();

        // GET: reservations
        public ActionResult Index()
        {
            var reservation = db.reservation.Include(r => r.customer).Include(r => r.product);
            return View(reservation.ToList());
        }

        // GET: reservations/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            reservation reservation = db.reservation.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: reservations/Create
        public ActionResult Create()
        {
            ViewBag.id_customer = new SelectList(db.customer, "id_customer", "names");
            ViewBag.id_product = new SelectList(db.product, "id_product", "name");
            return View();
        }

        // POST: reservations/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_reservation,id_customer,id_product")] reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.reservation.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_customer = new SelectList(db.customer, "id_customer", "names", reservation.id_customer);
            ViewBag.id_product = new SelectList(db.product, "id_product", "name", reservation.id_product);
            return View(reservation);
        }

        // GET: reservations/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            reservation reservation = db.reservation.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_customer = new SelectList(db.customer, "id_customer", "names", reservation.id_customer);
            ViewBag.id_product = new SelectList(db.product, "id_product", "name", reservation.id_product);
            return View(reservation);
        }

        // POST: reservations/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_reservation,id_customer,id_product")] reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_customer = new SelectList(db.customer, "id_customer", "names", reservation.id_customer);
            ViewBag.id_product = new SelectList(db.product, "id_product", "name", reservation.id_product);
            return View(reservation);
        }

        // GET: reservations/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            reservation reservation = db.reservation.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            reservation reservation = db.reservation.Find(id);
            db.reservation.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

outfit_project/outfit_project/Views/reservations/Create.cshtml
@model outfit_project.Models.reservation

@{
    ViewBag.Title = "Create";
}

<h2>Crear Reserva</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="input-field col s12 m12 l12">
                <i class="material-icons prefix">assignment_ind</i>
                @Html.DropDownList("id_customer", null, htmlAttributes: new { @class = "form-control" })
                @Html.LabelFor(model => model.id_customer, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationMessageFor(model => model.id_customer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12 m12 l12">
                <i class="material-icons prefix">assignment_ind</i>
                @Html.DropDownList("id_product", null, htmlAttributes: new { @class = "form-control" })
                @Html.LabelFor(model => model.id_product, "Producto", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationMessageFor(model => model.id_product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row center">
            <div class="col s12 m12 l12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Crear<i class="material-icons right">save</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>

    </div>
}

outfit_project/outfit_project/Views/reservations/Delete.cshtml
@model outfit_project.Models.reservation

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Seguro que desea eliminar esta reserva?</h3>
<div>
    <table class="striped">

        <thead>
            <tr>
                <th>Cliente</th>
                <th>Producto</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th>@Html.DisplayFor(model => model.customer.names)</th>
                <th>@Html.DisplayFor(model => model.product.name)</th>
            </tr>
        </tbody>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="row center">
            <div class="col s12 m12 l12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Eliminar<i class="material-icons right">delete_forever</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>
    }
</div>

outfit_project/outfit_project/Views/reservations/Details.cshtml
@model outfit_project.Models.reservation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>reservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.customer.document_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.customer.document_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_reservation }) |
    @Html.ActionLink("Back to List", "Index")
</p>

outfit_project/outfit_project/Views/reservations/Edit.cshtml
@model outfit_project.Models.reservation

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Reserva</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_reservation)

        <div class="row">
            <div class="input-field col s12 m12 l12">
                <i class="material-icons prefix">assignment_ind</i>
                @Html.DropDownList("id_customer", null, htmlAttributes: new { @class = "form-control" })
                @Html.LabelFor(model => model.id_customer, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationMessageFor(model => model.id_customer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12 m12 l12">
                <i class="material-icons prefix">assignment_ind</i>
                @Html.DropDownList("id_product", null, htmlAttributes: new { @class = "form-control" })
                @Html.LabelFor(model => model.id_product, "Producto", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationMessageFor(model => model.id_product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row center">
            <div class="col s12 m12 l12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Guardar Cambios<i class="material-icons right">save</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>

    </div>
}

outfit_project/outfit_project/Views/reservations/Index.cshtml
@model IEnumerable<outfit_project.Models.reservation>

@{
    ViewBag.Title = "Index";
}

<h2>Reservas</h2>

<form class="col s6">
    <div class="row">
        <div class="input-field col s3">
            <input placeholder="Buscar Reserva" id="SearchReserva" name="SearchReserva" type="text" class="validate">
        </div>
    </div>
</form>

<div class="row">
    <div class="col s1 m1 l1 center-align">
        <a class="black-text" href='@Url.Action("Create", "reservations")'><i class="material-icons icon medium">add_circle</i></a>
    </div>
</div>


<table class="striped" id="reservationList">
    <thead>
        <tr>
            <th>Cliente</th>
            <th>Producto</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.customer.names)</td>
                <td>@Html.DisplayFor(modelItem => item.product.name)</td>
                <td>
                    <a class="black-text" href='@Url.Action("Edit", "reservations", new { id = item.id_reservation })'><i class="material-icons">edit</i></a>
                </td>
                <td>|</td>
                <td>
                    <a class="black-text" href='@Url.Action("Delete", "reservations", new { id = item.id_reservation})'><i class="material-icons">delete</i></a>
                </td>
            </tr>
        }
    </tbody>

</table>