outfit_project/outfit_project/Models/product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outfit_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.reservation = new HashSet<reservation>();
        }
    
        public long id_product { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public long id_supplier { get; set; }
        public int stock { get; set; }
    
        public virtual supplier supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservation { get; set; }
    }
}

outfit_project/outfit_project/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using outfit_project.Models;

namespace outfit_project.Controllers
{
    public class productsController : Controller
    {
        private outfitEntities1 db = new outfitEntities1();

        // GET: products
        public ActionResult Index()
        {
            var product = db.product.Include(p => p.supplier);
            return View(product.ToList());
        }

        // GET: products/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: products/Create
        public ActionResult Create()
        {
            ViewBag.id_supplier = new SelectList(db.supplier, "id_supplier", "name");
            return View();
        }

        // POST: products/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_product,name,description,id_supplier,stock")] product product)
        {
            if (ModelState.IsValid)
            {
                db.product.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_supplier = new SelectList(db.supplier, "id_supplier", "name", product.id_supplier);
            return View(product);
        }

        // GET: products/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_supplier = new SelectList(db.supplier, "id_supplier", "name", product.id_supplier);
            return View(product);
        }

        // POST: products/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_product,name,description,id_supplier,stock")] product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_supplier = new SelectList(db.supplier, "id_supplier", "name", product.id_supplier);
            return View(product);
        }

        // GET: products/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            product product = db.product.Find(id);
            db.product.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

outfit_project/outfit_project/Views/products/Create.cshtml
@model outfit_project.Models.product

@{
    ViewBag.Title = "Create";
}

<h2>Crear Producto</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">local_offer</i>
                @Html.LabelFor(model => model.name, "Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">assessment</i>
                @Html.LabelFor(model => model.stock, "Cantidad", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12 m12 l12">
                <i class="material-icons prefix">description</i>
                @Html.LabelFor(model => model.description, "Descripción", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "materialize-textarea", id = "descriptionProduct" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12 m12 l12">
                <i class="material-icons prefix">assignment_ind</i>
                @Html.DropDownList("id_supplier", null, htmlAttributes: new { @class = "form-control" })
                @Html.LabelFor(model => model.id_supplier, "Proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationMessageFor(model => model.id_supplier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row center">
            <div class="col s12 m12 l12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Crear<i class="material-icons right">save</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>

    </div>
}

outfit_project/outfit_project/Views/products/Delete.cshtml
@model outfit_project.Models.product

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Seguro que desea eliminar este producto?</h3>
<div>
    <table class="striped">

        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Proveedor</th>
                <th>Cantidad</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th>@Html.DisplayFor(model => model.name)</th>
                <th>@Html.DisplayFor(model => model.description)</th>
                <th>@Html.DisplayFor(model => model.supplier.name)</th>
                <th>@Html.DisplayFor(model => model.stock)</th>
            </tr>
        </tbody>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="row center">
            <div class="col s12 m12 l12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Eliminar<i class="material-icons right">delete_forever</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>
    }
</div>

outfit_project/outfit_project/Views/products/Details.cshtml
@model outfit_project.Models.product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.supplier.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.supplier.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_product }) |
    @Html.ActionLink("Back to List", "Index")
</p>

outfit_project/outfit_project/Views/products/Edit.cshtml
@model outfit_project.Models.product

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Producto</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_product)

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">local_offer</i>
                @Html.LabelFor(model => model.name, "Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">assessment</i>
                @Html.LabelFor(model => model.stock, "Cantidad", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12 m12 l12">
                <i class="material-icons prefix">description</i>
                @Html.LabelFor(model => model.description, "Descripción", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "materialize-textarea", id = "descriptionProduct" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12 m12 l12">
                <i class="material-icons prefix">assignment_ind</i>
                @Html.DropDownList("id_supplier", null, htmlAttributes: new { @class = "form-control" })
                @Html.LabelFor(model => model.id_supplier, "Proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationMessageFor(model => model.id_supplier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row center">
            <div class="col s12 m12 l12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Guardar Cambios<i class="material-icons right">save</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>

    </div>
}

outfit_project/outfit_project/Views/products/Index.cshtml
@model IEnumerable<outfit_project.Models.product>

@{
    ViewBag.Title = "Index";
}

<h2>Productos</h2>

<form class="col s6">
    <div class="row">
        <div class="input-field col s3">
            <input placeholder="Buscar producto" id="SearchProduct" name="SearchProduct" type="text" class="validate">
        </div>
    </div>
</form>

<div class="row">
    <div class="col s1 m1 l1 center-align">
        <a class="black-text" href='@Url.Action("Create", "products")'><i class="material-icons icon medium">add_circle</i></a>
    </div>
</div>


<table class="striped" id="productList">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Proveedor</th>
            <th>Cantidad</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.name)</td>
                <td>@Html.DisplayFor(modelItem => item.description)</td>
                <td>@Html.DisplayFor(modelItem => item.supplier.name)</td>
                <td>@Html.DisplayFor(modelItem => item.stock)</td>
                <td>
                    <a class="black-text" href='@Url.Action("Edit", "products", new { id = item.id_product })'><i class="material-icons">edit</i></a>
                </td>
                <td>|</td>
                <td>
                    <a class="black-text" href='@Url.Action("Delete", "products", new { id = item.id_product})'><i class="material-icons">delete</i></a>
                </td>
            </tr>
        }
    </tbody>

</table>