outfit_project/outfit_project/Models/customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outfit_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.reservation = new HashSet<reservation>();
        }
    
        public long id_customer { get; set; }
        public string document_type { get; set; }
        public string document_number { get; set; }
        public string names { get; set; }
        public string last_names { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string city { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservation { get; set; }
    }
}

outfit_project/outfit_project/Controllers/customersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using outfit_project.Models;

namespace outfit_project.Controllers
{
    public class customersController : Controller
    {
        private outfitEntities1 db = new outfitEntities1();

        // GET: customers
        public ActionResult Index()
        {
            return View(db.customer.ToList());
        }

        // GET: customers/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: customers/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_customer,document_type,document_number,names,last_names,address,phone_number,email,city")] customer customer)
        {
            if (ModelState.IsValid)
            {
                db.customer.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: customers/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: customers/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_customer,document_type,document_number,names,last_names,address,phone_number,email,city")] customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: customers/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            customer customer = db.customer.Find(id);
            db.customer.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

outfit_project/outfit_project/Views/customers/Create.cshtml
@model outfit_project.Models.customer

@{
    ViewBag.Title = "Create";
}

<h2>Crear Cliente</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">credit_card</i>
                <select id="document_type" name="document_type">
                    <option value="CC">Cédula de ciudanía</option>
                    <option value="TI">Tarjeta de identidad</option>
                    <option value="CE">Cédula de extrangeria</option>
                    <option value="PAP">Pasaporte</option>
                    <option value="NIT">Número identificación tributaria</option>
                    <option value="NIP">Número identificación personal</option>
                </select>
                <label>Tipo de documento</label>
            </div>
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">featured_play_list</i>
                @Html.LabelFor(model => model.document_number, "Número de documento", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.document_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.document_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">account_circle</i>
                @Html.LabelFor(model => model.names, "Nombres", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.names, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.names, "", new { @class = "text-danger" })
            </div>
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">person</i>
                @Html.LabelFor(model => model.last_names, "Apellidos", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.last_names, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_names, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">add_location</i>
                @Html.LabelFor(model => model.address, "Dirección", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">call</i>
                @Html.LabelFor(model => model.phone_number, "Número de teléfono", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">email</i>
                @Html.LabelFor(model => model.email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">location_city</i>
                @Html.LabelFor(model => model.city, "Ciudad", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row center">
            <div class="col s12 m12 l12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Crear<i class="material-icons right">save</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>

    </div>
}

outfit_project/outfit_project/Views/customers/Delete.cshtml
@model outfit_project.Models.customer

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Seguro que desea eliminar este cliente?</h3>
<div>
    <table class="striped">

        <thead>
            <tr>
                <th>Tipo de documento</th>
                <th>Número de documento</th>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Dirección</th>
                <th>Télefono</th>
                <th>Email</th>
                <th>Ciudad</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th>@Html.DisplayFor(model => model.document_type)</th>
                <th>@Html.DisplayFor(model => model.document_number)</th>
                <th>@Html.DisplayFor(model => model.names)</th>
                <th>@Html.DisplayFor(model => model.last_names)</th>
                <th>@Html.DisplayFor(model => model.address)</th>
                <th>@Html.DisplayFor(model => model.phone_number)</th>
                <th>@Html.DisplayFor(model => model.email)</th>
                <th>@Html.DisplayFor(model => model.city)</th>
            </tr>
        </tbody>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="row center">
            <div class="col s12 m12 l12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Eliminar<i class="material-icons right">delete_forever</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>
    }
</div>

outfit_project/outfit_project/Views/customers/Details.cshtml
@model outfit_project.Models.customer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.document_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.document_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.document_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.document_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.names)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.names)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_names)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_names)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_customer }) |
    @Html.ActionLink("Back to List", "Index")
</p>

outfit_project/outfit_project/Views/customers/Edit.cshtml
@model outfit_project.Models.customer

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Cliente</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_customer)

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">credit_card</i>
                <select id="document_type" name="document_type">
                    <option value="CC">Cédula de ciudanía</option>
                    <option value="TI">Tarjeta de identidad</option>
                    <option value="CE">Cédula de extrangeria</option>
                    <option value="PAP">Pasaporte</option>
                    <option value="NIT">Número identificación tributaria</option>
                    <option value="NIP">Número identificación personal</option>
                </select>
                <label>Tipo de documento</label>
            </div>
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">featured_play_list</i>
                @Html.LabelFor(model => model.document_number, "Número de documento", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.document_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.document_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">account_circle</i>
                @Html.LabelFor(model => model.names, "Nombres", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.names, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.names, "", new { @class = "text-danger" })
            </div>
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">person</i>
                @Html.LabelFor(model => model.last_names, "Apellidos", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.last_names, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_names, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">add_location</i>
                @Html.LabelFor(model => model.address, "Dirección", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">call</i>
                @Html.LabelFor(model => model.phone_number, "Número de teléfono", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">email</i>
                @Html.LabelFor(model => model.email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
            <div class="input-field col s6 m6 l6">
                <i class="material-icons prefix">location_city</i>
                @Html.LabelFor(model => model.city, "Ciudad", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row center">
            <div class="col s12 m12 l12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Guardar Cambios<i class="material-icons right">save</i></button> | @Html.ActionLink("Volver", "Index")
            </div>
        </div>

    </div>
}

outfit_project/outfit_project/Views/customers/Index.cshtml
@model IEnumerable<outfit_project.Models.customer>

@{
    ViewBag.Title = "Index";
}

<h2>Clientes</h2>

<form class="col s6">
    <div class="row">
        <div class="input-field col s3">
            <input placeholder="Buscar cliente" id="SearchCustomer" name="SearchCustomer" type="text" class="validate">
        </div>
    </div>
</form>

<div class="row">
    <div class="col s1 m1 l1 center-align">
        <a class="black-text" href='@Url.Action("Create", "customers")'><i class="material-icons icon medium">add_circle</i></a>
    </div>
</div>


<table class="striped" id="customerList">
    <thead>
        <tr>
            <th>Tipo de documento</th>
            <th>Número de documento</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Dirección</th>
            <th>Télefono</th>
            <th>Email</th>
            <th>Ciudad</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.document_type)</td>
                <td>@Html.DisplayFor(modelItem => item.document_number)</td>
                <td>@Html.DisplayFor(modelItem => item.names)</td>
                <td>@Html.DisplayFor(modelItem => item.last_names)</td>
                <td>@Html.DisplayFor(modelItem => item.address)</td>
                <td>@Html.DisplayFor(modelItem => item.phone_number)</td>
                <td>@Html.DisplayFor(modelItem => item.email)</td>
                <td>@Html.DisplayFor(modelItem => item.city)</td>
                <td>
                    <a class="black-text" href='@Url.Action("Edit", "customers", new { id = item.id_customer })'><i class="material-icons">edit</i></a>
                </td>
                <td>|</td>
                <td>
                    <a class="black-text" href='@Url.Action("Delete", "customers", new { id = item.id_customer})'><i class="material-icons">delete</i></a>
                </td>
            </tr>
        }
    </tbody>

</table>